config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'user/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#show'
  get 'login', to: redirect('auth/:provider/callback'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create', as: :session
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'home#show'
  get 'profile', to: 'users#show', as: 'profile'

  resource :user do
    get :respositories, on: :member
    get 'repo/:name', to: 'users#repo_detail', as: :repo_detail
    get 'repo/:name/commits', to: 'users#repo_commits', as: :repo_commits
  end
end

app/models/application_record.rb
# frozen_string_literal: true

#
# Class ApplicationRecord provides base class for all models
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
# frozen_string_literal: true

#
# Class Authorization provides methods to intract with table
#
class Authorization < ApplicationRecord
  belongs_to :user
  validates :user_id, :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }

  def self.find_from_auth(auth)
    find_by(provider: auth['provider'], uid: auth['uid'])
  end

  def self.create_from_auth(auth, user = nil)
    user ||= User.find_or_create_from_auth_hash(auth)
    create(user_id: user.id, uid: auth.uid, provider: auth.provider,
           token: auth.credentials.token, username: auth.info.nickname)
  end
end

app/models/user.rb
# frozen_string_literal: true

#
# Class User provides methods to intract with users table
#
class User < ApplicationRecord
  has_many :authorizations, dependent: :destroy
  def self.find_or_create_from_auth_hash(auth)
    includes(:authorizations)
      .where(authorizations: { provider: auth.provider, uid: auth.uid })
      .first_or_initialize.tap do |user|
        fill_attributes(user, auth)
      end
  end

  def self.fill_attributes(user, auth)
    first, last = auth.info.name.split('-')
    user.first_name = first
    user.first_name = last
    user.email = auth.info.email
    user.picture = auth.info.image
    user.save!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

#
# Class ApplicationController provides base class for controllers
#
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  #
  # <check user authorization>
  #
  def authenticate
    redirect_to :login unless user_signed_in?
  end

  #
  # <find user from session >
  #
  #
  # @return [<object>] <current user from database>
  #
  def current_user
    @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  #
  # <check wether user is signed in or not>
  #
  #
  # @return [<boolean>] <description>
  #
  def user_signed_in?
    # converts current_user to a boolean by negating the negation
    !current_user.nil?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

#
# Class HomeController provides root actions
#
class HomeController < ApplicationController
  def show; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

#
# Class SessionsController provides for users sessions
#
class SessionsController < ApplicationController
  def new; end

  #
  # <create authorization object for current user>
  #
  def create
    @auth = Authorization.find_from_auth(auth_hash)
    if @auth.present?
      @auth = Authorization.create_from_auth(auth_hash, current_user)
    end
    session[:user_id] = @auth.user.id
    redirect_to profile_path
  end

  #
  # <destroy user session>
  #
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  #
  # <fetch authorization hash from omniauth response>
  #
  #
  # @return [<json>] <omniauth response>
  #
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

#
# Class UsersController for users actions
#
class UsersController < ApplicationController
  before_action :authenticate

  def show; end

  #
  # <fetch the names of repositories of a user>
  #
  #
  # @repo [<Array>] <contaning names of repositories>
  #
  def respositories
    response = Github::GithubApi.new(auth_provider).get('user/repos', {})
    @repos = Github::ApiResponseParser.extract_names(response, 'name')
  end

  #
  # <fetch details of given repository>
  #
  #
  # @repo_info [<hash>] <required info of repository>
  #
  def repo_detail
    response = Github::GithubApi.new(auth_provider).get(repo_url, {})
    @repo_info = Github::RepoDetailsParser.info_hash(response)
  end

  #
  # <fetch commits of a repository>
  #
  #
  # @commit_info [<Array of hash>] <containing required info>
  #
  def repo_commits
    response = Github::GithubApi.new(auth_provider).get(commit_url, date_params)
    @commit_info = Github::RepoDetailsParser.repo_commits(response)
  end

  private

  #
  # <fetch the authentication provider of user>
  #
  #
  # @return [<object>] <Authorization object of current_auth provider>
  #
  def auth_provider
    Authorization.find_by(user_id: @current_user.id, provider: provider_name)
  end

  #
  # <permit repo name in params>
  #
  def repo_name
    @repo_name = params.permit(:name).require(:name)
  end

  #
  # <permit date params>
  #
  def date_params
    @s_date = params[:since]
    @e_date = params[:until]
    params.permit(:since, :until)
  end

  #
  # <current provider name>
  #
  #
  # @return [<string>] <current provider name>
  #
  def provider_name
    'github'
  end

  #
  # <provide url for api commit action>
  #
  #
  # @return [<string, hash>] <url with params>
  #
  def commit_url
    repo_url + '/commits'
  end

  #
  # repo url provide dynamic url
  #
  #
  # @return [<string>] <url sting>
  #
  def repo_url
    "repos/#{auth_provider.username}/#{repo_name}"
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application helper
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# home helper
module HomeHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# session helper
module SessionsHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

# user helper
module UserHelper
end

app/views/home/show.html.erb
<div class="container">
  <div class="text-center">
  <h4 class="fw-300 c-grey-900 mB-40">Dummy App</h4>
 </div>
 <div class="row justify-content-md-center">
    <div class="col-md-6">
        <div class="form-group">
          <a href="/auth/github/" class="btn btn-outline-secondary btn-lg btn-block">Login with Github</a>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

app/views/layouts/_sidebar.html.erb
  <nav class="col-md-2 d-none d-md-block bg-light sidebar" style="height:500px;">
    <div class="sidebar-sticky">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="#">
             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Profile <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= respositories_user_path %>">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>Repositoties
          </a>
              <li class="nav-item">
                <a class="nav-link" href="<%=logout_path %>">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assingment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "#{controller_name}", "data-turbolinks-track": "load" %>
     <%= stylesheet_link_tag "#{controller_name}", "data-turbolinks-track": "load" %>
  </head>

  <body>
    <div>
      <div class="container-fluid">
      <div class="row">
      <%unless @current_user.nil? %>
      <%= render partial: "layouts/sidebar" %>
      <% end %>
      <div class="col-md-10">
       <%= yield %>
      </div>
    </div>
    </div>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h2> Please create your account</h2><br/> <br/>

<%= form_for :@user do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %><br/><br/>

 <%= f.label :email %>
 <%= f.text_field :email %><br/><br/>

 <%= f.label :password %>
 <%= f.text_field :password %><br/><br/>

 <%= f.submit value=”Signup”%>
<% end %><br/> <br/>

<h2><a href=’/auth/facebook’>Login with Github</a></h2>

app/views/users/repo_commits.html.erb
<div>
<input type="hidden" id="c_data" value="<%= "#{@commit_info.to_json}" %>">
<form method="get" url="/user/repo/:name/commits">
<input type="date" id="start_date" name="since" value="<%= @s_date %>">
<input type="date" id="end_date" name="until" value="<%= @e_date %>">
<input type="submit">
</form>
</div>
<style>

.chart rect {
  fill: steelblue;
}

.chart text {
  font: 10px sans-serif;
  text-anchor: end;
}

</style>
<svg class="chart"></svg>

app/views/users/repo_detail.html.erb
<div>
<div class="col-md-3 float-right">
<img src="<%=current_user.picture %>" class="rounded img-thumbnail" alt="...">
</div>
   <div class="col-md-6">
          <legend class="text-semibold">
            <i class="icon-file-text2 position-left"></i> Repository Details
          </legend>
          <div class="table-responsive">
            <table class="table table-borderless">
              <tbody>
                <tr>
                  <td style="width: 30%"><strong>Name:</td>
                  <td><%= @repo_info[:name] %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>Description:</strong></td>
                  <td><%= @repo_info[:description] %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>Language:</strong></td>
                  <td><%= @repo_info[:language]  %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>Default Branch:</strong></td>
                  <td><%= @repo_info[:default_branch] %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>Created At:</strong></td>
                  <td><%= @repo_info[:created_at]  %></td>
                </tr>
                 <tr>
                  <td style="width: 30%"><strong>Updated At:</strong></td>
                  <td><%= @repo_info[:updated_at]  %></td>
                </tr>
                 <tr>
                  <td style="width: 30%"><strong>Type:</strong></td>
                  <td><%= @repo_info[:type]  %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>Graphs:</strong></td>
                  <td><%= link_to "visual Commits", repo_commits_user_path(@repo_info[:name])  %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
</div>

app/views/users/respositories.html.erb
P<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Select Repo Name
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  	<% @repos.each do |repo_name| %>
    <a class="dropdown-item" href="<%=repo_detail_user_path("#{repo_name}")%>"><%=repo_name.humanize %></a>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
<div class="col-md-3 float-right">
<img src="<%=current_user.picture %>" class="rounded img-thumbnail" alt="...">
</div>
   <div class="col-md-6">
          <legend class="text-semibold">
            <i class="icon-file-text2 position-left"></i> Personal Details
          </legend>
          <div class="table-responsive">
            <table class="table table-borderless">
              <tbody>
                <tr>
                  <td style="width: 30%"><strong>Email:</strong></td>
                  <td><%= current_user.email %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>First Name:</strong></td>
                  <td><%= current_user.first_name.try(:titleize) %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>Last Name:</strong></td>
                  <td><%= current_user.last_name.try(:titleize)  %></td>
                </tr>
                <%current_user.authorizations.each do |auth| %>
                <tr>
                  <td style="width: 30%"><strong>Provider Name:</strong></td>
                  <td><%= auth.provider %></td>
                </tr>
                <tr>
                  <td style="width: 30%"><strong>UID:</strong></td>
                  <td><%= auth.uid  %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
</div>